"""Parameter-recovery test for DLAG on synthetic data generated by the
model's own prior.

Marked ``recovery`` (and ``slow``) so default ``uv run pytest`` skips it.
Run with ``uv run pytest -m recovery -k dlag``.

Recovery target (plan §5 Phase 3, calibrated to the engine's convergence
profile observed in PR 4b development):

- LL trace is (eventually) non-decreasing — average of last 3 LL values
  is well above the average of the first 3.
- Mean absolute correlation between recovered and true latent
  trajectories ``> 0.7`` (loose because latent identifiability holds
  only up to sign + orthogonal rotation; we average per-feature
  per-trial-time correlations after standardising).
- Recovered delay parameter RMSE vs ground truth ``< 0.4`` bins. EM in
  GP-hyperparameter space is linear-convergence so the iteration budget
  matters — we cap at 300 outer EM iterations with ``max_lbfgs_iter=40``
  inner LBFGS steps per Q-step. Empirically at those settings the test
  achieves ``RMSE ≈ 0.15`` on the synthetic scenario below.
- Recovered timescale ``γ`` relative error ``< 50%`` (the kernel is
  weakly identified without long trials; we only check the order of
  magnitude here, not high-precision recovery).
"""

from __future__ import annotations

import pytest
import torch

from mbrila import DLAG, ExactEMEngine, LatentSpec, MOSEKernel

pytestmark = [pytest.mark.recovery, pytest.mark.slow]


def _abs_corr(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    """Per-feature absolute correlation between two ``(N, K)`` tensors."""
    a_z = (a - a.mean(dim=0, keepdim=True)) / a.std(dim=0, keepdim=True).clamp(min=1e-8)
    b_z = (b - b.mean(dim=0, keepdim=True)) / b.std(dim=0, keepdim=True).clamp(min=1e-8)
    return (a_z * b_z).mean(dim=0).abs()


def test_dlag_recovers_delay_and_latents() -> None:
    """Generate from DLAG's prior, then re-fit and check parameter recovery.

    The ground-truth model has a single across latent with ``δ_{1} = +2``
    bins; the within latents pad each region with one extra factor. We
    use ``T = 30`` and ``B = 40`` trials — modest by DLAG's normal
    standards but plenty for the prior to be identifiable.
    """
    torch.manual_seed(0)

    # 1) Build a ground-truth DLAG and sample from it.
    spec = LatentSpec(n_across=1, n_within=(1, 1))
    truth = DLAG(
        latent_spec=spec,
        y_dims=(8, 8),
        T=30,
        kernel_factory_across=lambda: MOSEKernel(num_regions=2, init_sigma=0.04),  # σ ≈ 5-bin
        kernel_factory_within=lambda: MOSEKernel(num_regions=1, init_sigma=0.04),
        max_delay=8.0,
        device="cpu",
        dtype=torch.float64,
    )
    # Make ground truth non-trivial: set a real delay and a smooth C.
    target_delay = 2.0
    beta_true = 2.0 * torch.atanh(torch.tensor(target_delay / 8.0, dtype=torch.float64))
    with torch.no_grad():
        truth.dynamics.delay.beta.fill_(beta_true.item())
        # A simple smooth C: linear ramp + noise so the cross-region
        # alignment is genuinely informative.
        for C_r in truth.observation.Cs:
            C_r.data = torch.linspace(-1.0, 1.0, C_r.numel(), dtype=torch.float64).view_as(C_r)
            C_r.data += 0.05 * torch.randn_like(C_r.data)
        truth.observation.diag_R_param.data.fill_(0.05)

    data = truth.sample(n_trials=40, T=30, seed=0)

    # 2) Build a fresh model, initialise via CCA, and fit.
    # Use a larger LBFGS budget than the engine default — the GP M-step's
    # Q-surface changes after each E-step and a deeper local search per
    # outer iteration measurably accelerates δ recovery. Empirically
    # (PR 4b probe) at these settings: δ̂ ≈ +1.86 after 300 EM iters
    # (truth = +2.0, RMSE ≈ 0.14); δ̂ ≈ +2.03 after 500 iters.
    engine = ExactEMEngine(max_lbfgs_iter=40, lbfgs_history=15)
    model = DLAG(
        latent_spec=spec,
        y_dims=(8, 8),
        T=30,
        kernel_factory_across=lambda: MOSEKernel(num_regions=2, init_sigma=0.02),  # deliberately a bit off
        kernel_factory_within=lambda: MOSEKernel(num_regions=1, init_sigma=0.02),
        max_delay=8.0,
        engine="exact",
        engine_override=engine,
        device="cpu",
        dtype=torch.float64,
    )
    model.initialize_from_data(data, mode="pcca")
    result = model.fit(data, max_iter=300, tol=1e-8)

    # ----- 1. LL trajectory ----------------------------------------------
    early = sum(result.score_trace[:3]) / 3
    late = sum(result.score_trace[-3:]) / 3
    assert late > early, f"LL did not improve: early={early:.2f}  late={late:.2f}"

    # ----- 2. Latent recovery --------------------------------------------
    posterior = model.infer(data)
    # Build true latents by reproducing the sample's noise-free latent state.
    # For checking we use posterior means under the FITTED model — i.e.
    # correlate fitted x_hat with truth's x_hat. This is the standard
    # latent-correlation test used elsewhere in the codebase.
    truth_posterior = truth.infer(data)
    a_flat = truth_posterior.mean.reshape(-1, truth_posterior.mean.shape[-1])
    b_flat = posterior.mean.reshape(-1, posterior.mean.shape[-1])
    corrs = _abs_corr(a_flat, b_flat)
    assert corrs.mean().item() > 0.7, f"mean |corr| too low: {corrs.tolist()}"

    # ----- 3. Delay recovery ---------------------------------------------
    learned_delay = model.dynamics.delay.as_tensor()  # (R, K_a)
    true_delay = truth.dynamics.delay.as_tensor()
    rmse = (learned_delay - true_delay).pow(2).mean().sqrt().item()
    assert rmse < 0.4, f"delay RMSE too high: {rmse:.3f}"

    # ----- 4. Timescale recovery (order of magnitude) --------------------
    gamma_hat = torch.exp(model.dynamics.kernel_across[0].log_sigma).item()
    gamma_true = torch.exp(truth.dynamics.kernel_across[0].log_sigma).item()
    rel_err = abs(gamma_hat - gamma_true) / gamma_true
    assert rel_err < 0.5, f"γ_across relative error too high: {rel_err:.3f}"
